// <auto-generated>
//     This code was generated by a tool from a template stored in:
//     '..\odatasdkcodesamples\ODataValidationToolkit\4.0\ODataTestGen\TestTemplates\Delete\Sample Delete.tt'
//     Generation time: 12/08/2010 16:12:23
// </auto-generated>
	





namespace ODataGeneratedTests
{
    	
    using System;
    using System.Linq;
    using System.IO;
    using System.Data.Services;
    using System.Xml.Linq;
    using System.Net;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using System.Collections.Generic;
    using System.Text;
    using AtomPayloadAnalyzer;
    using System.Xml;
    
    [TestClass]
    public class Sample_Delete
    {
        		
        /// <summary>
        /// It is a sample showing how to get permission levels on each entity set in T4 templates 
        /// </summary>
        [TestMethod]
        public void SampleDeleteOnCategories()
        {
            //  entityName: Categories
            //  entitySetUri: http://localhost:3879/IQDSP.svc/Categories
            //	CanGet: true
            //  CanPut: true
            //  CanPost: true
            //  CanDelete: true
        }

        /// <summary>
        /// It is a sample showing how to get permission levels on each entity set in T4 templates 
        /// </summary>
        [TestMethod]
        public void SampleDeleteOnCustomerCustomerDemos()
        {
            //  entityName: CustomerCustomerDemos
            //  entitySetUri: http://localhost:3879/IQDSP.svc/CustomerCustomerDemos
            //	CanGet: true
            //  CanPut: true
            //  CanPost: true
            //  CanDelete: true
        }

        /// <summary>
        /// It is a sample showing how to get permission levels on each entity set in T4 templates 
        /// </summary>
        [TestMethod]
        public void SampleDeleteOnCustomerDemographics()
        {
            //  entityName: CustomerDemographics
            //  entitySetUri: http://localhost:3879/IQDSP.svc/CustomerDemographics
            //	CanGet: true
            //  CanPut: true
            //  CanPost: true
            //  CanDelete: true
        }

        /// <summary>
        /// It is a sample showing how to get permission levels on each entity set in T4 templates 
        /// </summary>
        [TestMethod]
        public void SampleDeleteOnCustomers()
        {
            //  entityName: Customers
            //  entitySetUri: http://localhost:3879/IQDSP.svc/Customers
            //	CanGet: true
            //  CanPut: true
            //  CanPost: true
            //  CanDelete: true
        }

        /// <summary>
        /// It is a sample showing how to get permission levels on each entity set in T4 templates 
        /// </summary>
        [TestMethod]
        public void SampleDeleteOnEmployees()
        {
            //  entityName: Employees
            //  entitySetUri: http://localhost:3879/IQDSP.svc/Employees
            //	CanGet: true
            //  CanPut: true
            //  CanPost: true
            //  CanDelete: true
        }

        /// <summary>
        /// It is a sample showing how to get permission levels on each entity set in T4 templates 
        /// </summary>
        [TestMethod]
        public void SampleDeleteOnEmployeeTerritories()
        {
            //  entityName: EmployeeTerritories
            //  entitySetUri: http://localhost:3879/IQDSP.svc/EmployeeTerritories
            //	CanGet: true
            //  CanPut: true
            //  CanPost: true
            //  CanDelete: true
        }

        /// <summary>
        /// It is a sample showing how to get permission levels on each entity set in T4 templates 
        /// </summary>
        [TestMethod]
        public void SampleDeleteOnOrderDetails()
        {
            //  entityName: OrderDetails
            //  entitySetUri: http://localhost:3879/IQDSP.svc/OrderDetails
            //	CanGet: true
            //  CanPut: true
            //  CanPost: true
            //  CanDelete: true
        }

        /// <summary>
        /// It is a sample showing how to get permission levels on each entity set in T4 templates 
        /// </summary>
        [TestMethod]
        public void SampleDeleteOnOrders()
        {
            //  entityName: Orders
            //  entitySetUri: http://localhost:3879/IQDSP.svc/Orders
            //	CanGet: true
            //  CanPut: true
            //  CanPost: true
            //  CanDelete: true
        }

        /// <summary>
        /// It is a sample showing how to get permission levels on each entity set in T4 templates 
        /// </summary>
        [TestMethod]
        public void SampleDeleteOnProducts()
        {
            //  entityName: Products
            //  entitySetUri: http://localhost:3879/IQDSP.svc/Products
            //	CanGet: true
            //  CanPut: true
            //  CanPost: true
            //  CanDelete: true
        }

        /// <summary>
        /// It is a sample showing how to get permission levels on each entity set in T4 templates 
        /// </summary>
        [TestMethod]
        public void SampleDeleteOnRegions()
        {
            //  entityName: Regions
            //  entitySetUri: http://localhost:3879/IQDSP.svc/Regions
            //	CanGet: true
            //  CanPut: true
            //  CanPost: true
            //  CanDelete: true
        }

        /// <summary>
        /// It is a sample showing how to get permission levels on each entity set in T4 templates 
        /// </summary>
        [TestMethod]
        public void SampleDeleteOnShippers()
        {
            //  entityName: Shippers
            //  entitySetUri: http://localhost:3879/IQDSP.svc/Shippers
            //	CanGet: true
            //  CanPut: true
            //  CanPost: true
            //  CanDelete: true
        }

        /// <summary>
        /// It is a sample showing how to get permission levels on each entity set in T4 templates 
        /// </summary>
        [TestMethod]
        public void SampleDeleteOnSuppliers()
        {
            //  entityName: Suppliers
            //  entitySetUri: http://localhost:3879/IQDSP.svc/Suppliers
            //	CanGet: true
            //  CanPut: true
            //  CanPost: true
            //  CanDelete: true
        }

        /// <summary>
        /// It is a sample showing how to get permission levels on each entity set in T4 templates 
        /// </summary>
        [TestMethod]
        public void SampleDeleteOnTerritories()
        {
            //  entityName: Territories
            //  entitySetUri: http://localhost:3879/IQDSP.svc/Territories
            //	CanGet: true
            //  CanPut: true
            //  CanPost: true
            //  CanDelete: true
        }

    }
}
